---
config:
  flowchart:
    htmlLabels: false
  htmlLabels: false
  theme: base
---
block-beta
    columns 1
    A["Applications finales : IA génératives, etc..."]
    B["Couche haute : K3s en haute disponibilité"]
    C["Couche basse : antsd et Serf"]
    D["Matériel et système d'exploitation : Raspberry Pi sous ants-os"]

    style A fill:#ECEFF1,stroke:#546E7A,color:#000
    style B fill:#ECEFF1,stroke:#546E7A,color:#000
    style C fill:#BBDEFB, stroke:#0D47A1,color:#000
    style D fill:#ECEFF1,stroke:#546E7A,color:#000
