UsePAM yes

PubkeyAuthentication yes
PermitRootLogin no
PasswordAuthentication no

PermitEmptyPasswords no
ChallengeResponseAuthentication no
X11Forwarding no
AllowAgentForwarding no
PermitTunnel no
KbdInteractiveAuthentication no

MaxAuthTries 3