package k3s

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/jeremie-arcidiacono/Zero-Config-HA-Cluster/antsd/internal/node"
)

const (
	// installScriptPath is the K3s install script bundled in the ants-os image.
	installScriptPath = "/usr/local/bin/install-k3s.sh"

	// serverUninstallScriptPath and agentUninstallScriptPath are the self-uninstall scripts
	// generated by the install script.
	serverUninstallScriptPath = "/usr/local/bin/k3s-uninstall.sh"
	agentUninstallScriptPath  = "/usr/local/bin/k3s-agent-uninstall.sh"

	// binPath is the K3s binary bundled in the ants-os image.
	binPath = "/usr/local/bin/k3s"

	// imagesPath is where K3s looks for the container image archives it loads at startup.
	imagesPath = "/var/lib/rancher/k3s/agent/images"

	// vaultPath holds the ants-os copies of the assets an offline installation needs.
	vaultPath = "/usr/lib/ants/k3s"

	// vaultBinName and vaultImagesName are the vault entries matching binPath and imagesPath.
	vaultBinName    = "k3s"
	vaultImagesName = "images"

	// agentKubeconfigPath is the kubelet credential written by the K3s agent.
	agentKubeconfigPath = "/var/lib/rancher/k3s/agent/kubelet.kubeconfig"

	// systemdUnitDir is where the K3s install script writes its service unit.
	systemdUnitDir = "/etc/systemd/system"

	// systemdServerUnit and systemdAgentUnit are the service units created by the K3s install script.
	// Their presence shows the role of an existing installation.
	systemdServerUnit = "k3s.service"
	systemdAgentUnit  = "k3s-agent.service"

	// readyPollInterval is the delay between two readiness probes.
	readyPollInterval = 3 * time.Second

	// readyLogEvery is the number of failed probes between two warnings, so
	// that an unbounded wait stays visible in the logs without flooding them.
	readyLogEvery = 20
)

// ExecInstaller drives the K3s installation by executing the install script.
type ExecInstaller struct {
	logger *slog.Logger

	// token is the pre-shared cluster join token (identical on every node).
	token string

	// unitDir is the systemd unit directory.
	unitDir string

	// binPath, imagesDir and vaultDir locate the air-gap assets.
	binPath   string
	imagesDir string
	vaultDir  string
}

// NewExecInstaller returns an Installer that runs the install script.
func NewExecInstaller(token string, logger *slog.Logger) *ExecInstaller {
	return &ExecInstaller{
		logger:    logger,
		token:     token,
		unitDir:   systemdUnitDir,
		binPath:   binPath,
		imagesDir: imagesPath,
		vaultDir:  vaultPath,
	}
}

func (i *ExecInstaller) InstallServerInit(ctx context.Context) error {
	return i.runInstallScript(ctx, []string{
		"INSTALL_K3S_EXEC=server --cluster-init",
	})
}

func (i *ExecInstaller) InstallServerJoin(ctx context.Context, serverIP string) error {
	return i.runInstallScript(ctx, []string{
		fmt.Sprintf("INSTALL_K3S_EXEC=server --server %s", joinURL(serverIP)),
	})
}

func (i *ExecInstaller) InstallAgent(ctx context.Context, serverIP string) error {
	return i.runInstallScript(ctx, []string{
		"INSTALL_K3S_EXEC=agent",
		"K3S_URL=" + joinURL(serverIP),
	})
}

// Convert replaces the local K3s installation with the other role, joining the cluster
// through the server at serverIP. It is the local part of the rescaling workflow.
// It returns an error when the node has no installation to convert, or an ambiguous one.
func (i *ExecInstaller) Convert(ctx context.Context, to node.Role, serverIP string) error {
	from, err := i.InstalledRole(ctx)
	if err != nil {
		return fmt.Errorf("cannot convert this node to %q: %w", to, err)
	}
	if from == to {
		i.logger.Warn("k3s already runs the target role, nothing to convert", "role", to)
		return nil
	}

	if err := i.runUninstallScript(ctx, from); err != nil {
		return err
	}

	// The absence of a systemd unit proves the node is ready for the new installation
	// (we don't trust uninstall script exit code, same as the install script)
	if role, err := i.InstalledRole(ctx); !errors.Is(err, ErrNotInstalled) {
		return fmt.Errorf("k3s uninstall left an installation behind (role %q, error %v)", role, err)
	}

	if to == node.RoleServer {
		return i.InstallServerJoin(ctx, serverIP)
	}
	return i.InstallAgent(ctx, serverIP)
}

// runUninstallScript runs the self-uninstall script of the installed role.
//
// A failure is reported but not returned: the script is unreliable by construction (see Convert),
// so the caller decides from the state it left behind, not from its exit code.
func (i *ExecInstaller) runUninstallScript(ctx context.Context, role node.Role) error {
	script := serverUninstallScriptPath
	if role == node.RoleAgent {
		script = agentUninstallScriptPath
	}

	i.logger.Info("running k3s uninstall script", "script", script)

	output, err := exec.CommandContext(ctx, script).CombinedOutput()
	if err != nil {
		i.logger.Warn("k3s uninstall script reported a failure",
			"role", role, "error", err, "output", tail(output))
		return ctx.Err() // A canceled antsd must stop here rather than reinstall.
	}

	i.logger.Debug("k3s uninstall script completed", "output", string(output))
	return nil
}

// stageAirGapAssets restores, from the ants-os asset vault, the files an offline
// installation needs (K3s binary, air-gap container image archives).
//
// The uninstall script deletes those files so a node that converts its role would have nothing left to reinstall from.
// So a pristine copy is kept where K3s never look.
func (i *ExecInstaller) stageAirGapAssets(ctx context.Context) error {
	if err := ctx.Err(); err != nil {
		return err // Do not start potentially long task (copyFile) when the context is already canceled.
	}

	if _, err := os.Stat(i.vaultDir); err != nil {
		return fmt.Errorf("stat the air-gap asset vault %s: %w", i.vaultDir, err)
	}

	if err := i.stageAsset(filepath.Join(i.vaultDir, vaultBinName), i.binPath, 0o755); err != nil {
		return err
	}

	vaultImages := filepath.Join(i.vaultDir, vaultImagesName)
	archives, err := os.ReadDir(vaultImages)
	if err != nil {
		return fmt.Errorf("read the vaulted image archives %s: %w", vaultImages, err)
	}

	for _, archive := range archives {
		if archive.IsDir() {
			continue
		}
		src := filepath.Join(vaultImages, archive.Name())
		if err := i.stageAsset(src, filepath.Join(i.imagesDir, archive.Name()), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// stageAsset puts the vaulted src at dst, by hard link when the filesystem allows it.
// An existing dst is not replaced (do not override live binaries)
func (i *ExecInstaller) stageAsset(src, dst string, mode os.FileMode) error {
	switch _, err := os.Stat(dst); {
	case err == nil:
		return nil // dst already present
	case !errors.Is(err, os.ErrNotExist):
		return fmt.Errorf("stat %s: %w", dst, err)
	}

	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(dst), err)
	}

	if err := os.Link(src, dst); err != nil {
		i.logger.Debug("hard link refused, falling back to a copy",
			"source", src, "destination", dst, "error", err)
		if err := copyFile(src, dst, mode); err != nil {
			return fmt.Errorf("restore %s from the air-gap asset vault: %w", dst, err)
		}
	} else if err := os.Chmod(dst, mode); err != nil { // Ensure the mode in the vault has not changed (just to be safe)
		return fmt.Errorf("set the mode of %s: %w", dst, err)
	}

	i.logger.Debug("air-gap asset restored from the vault", "source", src, "destination", dst)
	return nil
}

// copyFile is the fallback of stageAsset, for the case where src and dst cannot use a hard link.
func copyFile(src, dst string, mode os.FileMode) error {
	source, err := os.Open(src)
	if err != nil {
		return err
	}
	defer func() { _ = source.Close() }()

	tmp, err := os.CreateTemp(filepath.Dir(dst), filepath.Base(dst)+".tmp-*")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(tmp.Name()) }() // It does nothing if the rename succeeds

	if _, err := io.Copy(tmp, source); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), dst)
}

// runInstallScript executes the install script with the air-gap environment
// plus the mode-specific variables in extraEnv.
// It ensures that the assets needed for the installation are available (taken from the vault).
func (i *ExecInstaller) runInstallScript(ctx context.Context, extraEnv []string) error {
	if err := i.stageAirGapAssets(ctx); err != nil {
		return fmt.Errorf("prepare the air-gap assets: %w", err)
	}

	cmd := exec.CommandContext(ctx, installScriptPath)
	cmd.Env = append(os.Environ(),
		"INSTALL_K3S_SKIP_DOWNLOAD=true",
		"K3S_TOKEN="+i.token,
	)
	cmd.Env = append(cmd.Env, extraEnv...)

	i.logger.Info("running k3s install script", "mode_env", extraEnv)

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("k3s install script failed: %w (output: %s)", err, tail(output))
	}

	i.logger.Debug("k3s install script completed", "output", string(output))
	return nil
}

// WaitServerReady polls the local Kubernetes API readiness endpoint through
// "k3s kubectl" until it answers OK or ctx is canceled.
func (i *ExecInstaller) WaitServerReady(ctx context.Context) error {
	return i.pollUntilReady(ctx, "server", func(ctx context.Context) error {
		probe := exec.CommandContext(ctx, i.binPath, "kubectl", "get", "--raw=/readyz")
		if output, err := probe.CombinedOutput(); err != nil {
			return fmt.Errorf("%w (output: %s)", err, tail(output))
		}
		return nil
	})
}

// WaitAgentReady polls the cluster through "k3s kubectl"
// until it reports this node as Ready or ctx is canceled.
//
// An agent hosts no API server, so readiness has to be asked of the control plane.
func (i *ExecInstaller) WaitAgentReady(ctx context.Context) error {
	// todo : use same name in config, serf and k3s
	hostname, err := os.Hostname()
	if err != nil {
		return fmt.Errorf("resolve hostname used as the k3s node name: %w", err)
	}
	nodeName := strings.ToLower(strings.TrimSpace(hostname)) // DNS RFC-1123 name rule

	const readyConditionPath = `jsonpath={.status.conditions[?(@.type=="Ready")].status}`

	return i.pollUntilReady(ctx, "agent", func(ctx context.Context) error {
		probe := exec.CommandContext(ctx, i.binPath, "kubectl",
			"--kubeconfig", agentKubeconfigPath,
			"get", "node", nodeName, // Limit the scope to this node only, because an agent is not authorized to get all nodes
			"-o", readyConditionPath)

		output, err := probe.CombinedOutput()
		if err != nil {
			return fmt.Errorf("%w (output: %s)", err, tail(output))
		}
		if condition := strings.TrimSpace(string(output)); condition != "True" {
			return fmt.Errorf("node %q is not Ready yet (condition: %q)", nodeName, condition)
		}
		return nil
	})
}

// InstalledRole recovers the role of an existing installation from the name of
// the systemd unit created by the installation script.
//
// Finding both units means a previous installation was not cleaned up before
// another one ran: the node is in an ambiguous state.
func (i *ExecInstaller) InstalledRole(context.Context) (node.Role, error) {
	hasServer, err := systemdUnitExists(filepath.Join(i.unitDir, systemdServerUnit))
	if err != nil {
		return "", err
	}
	hasAgent, err := systemdUnitExists(filepath.Join(i.unitDir, systemdAgentUnit))
	if err != nil {
		return "", err
	}

	switch {
	case hasServer && hasAgent:
		return "", fmt.Errorf("ambiguous k3s installation: both %s and %s exist in %s",
			systemdServerUnit, systemdAgentUnit, i.unitDir)
	case hasServer:
		return node.RoleServer, nil
	case hasAgent:
		return node.RoleAgent, nil
	default:
		return "", fmt.Errorf("no k3s unit found in %s: %w", i.unitDir, ErrNotInstalled)
	}
}

// systemdUnitExists reports whether a systemd unit file is present.
func systemdUnitExists(path string) (bool, error) {
	switch _, err := os.Stat(path); {
	case err == nil:
		return true, nil
	case errors.Is(err, os.ErrNotExist):
		return false, nil
	default:
		return false, fmt.Errorf("stat %s: %w", path, err)
	}
}

// pollUntilReady runs probe every readyPollInterval until it succeeds or the
// context is canceled.
// role only labels the logs.
// The wait is unbounded: the deadline belongs to the caller.
func (i *ExecInstaller) pollUntilReady(ctx context.Context, role string, probe func(context.Context) error) error {
	ticker := time.NewTicker(readyPollInterval)
	defer ticker.Stop()

	started := time.Now()
	for attempt := 1; ; attempt++ {
		err := probe(ctx)
		if err == nil {
			i.logger.Info("local k3s is ready", "role", role, "waited", time.Since(started).Round(time.Second))
			return nil
		}

		// The first failures are expected (K3s is still starting).
		// Report periodically so that a node stuck waiting forever still remains visible.
		if attempt%readyLogEvery == 0 {
			i.logger.Warn("k3s still not ready",
				"role", role, "attempts", attempt,
				"waited", time.Since(started).Round(time.Second), "error", err)
		} else {
			// todo remove this ?
			i.logger.Debug("k3s not ready yet", "role", role, "attempt", attempt, "error", err)
		}

		select {
		case <-ctx.Done():
			return fmt.Errorf("gave up waiting for k3s %s readiness after %s: %w (last probe error: %v)",
				role, time.Since(started).Round(time.Second), ctx.Err(), err)
		case <-ticker.C:
		}
	}
}

// tail returns the last part of a command output.
// Used to keep error messages short.
func tail(output []byte) string {
	const maxLen = 1024
	output = bytes.TrimSpace(output)
	if len(output) > maxLen {
		output = output[len(output)-maxLen:]
	}
	return string(output)
}
